# general settings
homeassistant:
  name: Home
  country: KR
  language: ko
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  currency: EUR
  time_zone: Asia/Seoul
  external_url: !secret external_url
  internal_url: !secret internal_url

# enables configuration ui
config:

# incorporate latest changes
default_config:

# modify logger
logger:
  default: warn
  logs:
    homeassistant.setup: warn
    homeassistant.loader: warn
    homeassistant.helpers.entity: warn
    homeassistant.config_entries: warn
    homeassistant.components.http.ban: warn
    homeassistant.components.discovery: warn
    homeassistant.components.upnp: warn
    homeassistant.components.ipp: warn
    pyhap.hap_server: warn
    fritzconnection: info

# database recorder
recorder:
  db_url: !secret recorder_url

  auto_purge: true
  purge_keep_days: 14

  include:
    domains:
      - alarm_control_panel
      - automation
      - binary_sensor
      - climate
      - cover
      - device_tracker
      - group
      - input_boolean
      - input_number
      - input_select
      - input_text
      - light
      - media_player
      - person
      - remote
      - script
      - sensor
      - switch
      - timer
      - vacuum

  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.detection_fps
      - sensor.doorbell_camera_fps
      - sensor.doorbell_detection_fps
      - sensor.doorbell_process_fps
      - sensor.doorbell_skipped_fps
      - sensor.time
      - sensor.time_utc
      - sensor.system_time_of_day_detailed
      - sensor.living_area_vacuum_map

    entity_globs:
      - sensor.highfell_*
      - sensor.iphone_bernd_*
      - sensor.iphone_man_yie_*
      - sensor.macbook_bernd_*

# enable themes
frontend:
  themes: !include_dir_merge_named ../themes

# enable ios frontend
ios:

# enable wake on lan
wake_on_lan:

# split imports
automation: !include_dir_list ../automations
group: !include_dir_merge_named ../groups
scene: !include_dir_merge_list ../scenes
script: !include_dir_merge_named ../scripts
sensor: !include_dir_merge_list ../sensors
switch: !include_dir_merge_list ../switches
template: !include_dir_merge_list ../templates
# input_boolean: !include_dir_merge_named ../helpers/booleans
