http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 172.16.0.0/12
  - 127.0.0.1
  - !secret http_trusted_proxy_1
  - !secret http_trusted_proxy_2
  - !secret http_trusted_proxy_3
  - !secret http_trusted_proxy_4
