---
logger:
  default: warn
  logs:
    homeassistant.setup: warn
    homeassistant.loader: warn
    homeassistant.helpers.entity: warn
    homeassistant.config_entries: warn
    homeassistant.components.http.ban: warn
    homeassistant.components.discovery: warn
    homeassistant.components.upnp: warn
    homeassistant.components.ipp: warn
    pyhap.hap_server: warn
    fritzconnection: info
