git submodule add https://github.com/AalianKhan/mushroom-strategy.git ./config/www/mushroom-strategy
git submodule add https://github.com/AnthonMS/my-cardsz.git ./config/www/my-cardsz
git submodule add https://github.com/Makin-Things/weather-radar-card.git ./config/www/weather-radar-card
git submodule add https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card.git ./config/www/lovelace-xiaomi-vacuum-map-card
git submodule add https://github.com/benct/lovelace-github-entity-row.git ./config/www/lovelace-github-entity-row
git submodule add https://github.com/benct/lovelace-multiple-entity-row.git ./config/www/lovelace-multiple-entity-row
git submodule add https://github.com/bokub/rgb-light-card.git ./config/www/rgb-light-card
git submodule add https://github.com/bramkragten/swipe-card.git ./config/www/swipe-card
git submodule add https://github.com/cbulock/lovelace-battery-entity.git ./config/www/lovelace-battery-entity
git submodule add https://github.com/custom-cards/button-card.git ./config/www/button-card
git submodule add https://github.com/kalkih/mini-graph-card.git ./config/www/mini-graph-card
git submodule add https://github.com/kalkih/mini-media-player.git ./config/www/mini-media-player
git submodule add https://github.com/kalkih/simple-weather-card.git ./config/www/simple-weather-card
git submodule add https://github.com/ljmerza/light-entity-card.git ./config/www/light-entity-card
git submodule add https://github.com/piitaya/lovelace-mushroom.git ./config/www/lovelace-mushroom
git submodule add https://github.com/thomasloven/lovelace-auto-entities.git ./config/www/lovelace-auto-entities
git submodule add https://github.com/thomasloven/lovelace-card-mod.git ./config/www/lovelace-card-mod
git submodule add https://github.com/thomasloven/lovelace-layout-card.git ./config/www/lovelace-layout-card
git submodule add https://github.com/thomasloven/lovelace-slider-entity-row.git ./config/www/lovelace-slider-entity-row
git submodule add https://github.com/thomasloven/lovelace-state-switch.git ./config/www/lovelace-state-switch
