homeassistant:
  packages: !include_dir_named integrations

  name: Home
  country: KR
  language: ko
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  currency: KRW
  time_zone: Asia/Seoul
  external_url: !secret homeassistant_external_url
  internal_url: !secret homeassistant_internal_url
  auth_providers:
  - type: homeassistant
