---

homeassistant_elevation: ""
homeassistant_latitude: ""
homeassistant_longitude: ""
homeassistant_external_url: ""
homeassistant_internal_url: ""

notify_html5_vapid_prv_key: ""
notify_html5_vapid_pub_key: ""
notify_html5_vapid_email: ""

recorder_db_url: ""

http_trusted_proxies:
- 172.16.0.0/12
- 127.0.0.1

z2m_advanced_network_key: []
z2m_mqtt_password: ""
